### ISSUE TITLE
Test failure 

### ISSUE THREAD

**Issue by jihadbaeth** [Data-to-Insight-Center/komadu#6]
Hello @isurues  

I was able to successfully build komadu by following the guide you provided however when running the axis2-client-core tests I'm getting some errors and nothing I've tried seems to solve this problem. I wonder if you can figure out what I've missed out here by taking a look at the errors 

Thanks in advance 
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Komadu Axis2 Client Core 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ komadu-axis2-client-core ---
[INFO] Deleting /home/vagrant/komadu/komadu-master/axis2-client-core/target
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-source (add-source) @ komadu-axis2-client-core ---
[INFO] Source directory: /home/vagrant/komadu/komadu-master/axis2-client-core/target/generated-code/src added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ komadu-axis2-client-core ---
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/vagrant/komadu/komadu-master/axis2-client-core/src/main/resources
[INFO] 
[INFO] --- maven-antrun-plugin:1.1:run (source-code-generation) @ komadu-axis2-client-core ---
[INFO] Executing tasks
     [java] Retrieving document at 'config/KomaduService.wsdl'.
     [java] Retrieving schema at 'komadu_query_schema.xsd', relative to 'file:/home/vagrant/komadu/komadu-master/axis2-client-core/config/KomaduService.wsdl'.
     [java] Retrieving schema at 'komadu_ingest_schema.xsd', relative to 'file:/home/vagrant/komadu/komadu-master/axis2-client-core/config/komadu_query_schema.xsd'.
     [java] Retrieving schema at 'prov-20130307.xsd', relative to 'file:/home/vagrant/komadu/komadu-master/axis2-client-core/config/komadu_query_schema.xsd'.
     [java] Retrieving schema at 'xml.xsd', relative to 'file:/home/vagrant/komadu/komadu-master/axis2-client-core/config/prov-20130307.xsd'.
     [java] Retrieving schema at 'komadu_ingest_schema.xsd', relative to 'file:/home/vagrant/komadu/komadu-master/axis2-client-core/config/KomaduService.wsdl'.
     [java] log4j:WARN No appenders could be found for logger (org.apache.axis2.description.WSDL11ToAllAxisServicesBuilder).
     [java] log4j:WARN Please initialize the log4j system properly.
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ komadu-axis2-client-core ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[INFO] Compiling 590 source files to /home/vagrant/komadu/komadu-master/axis2-client-core/target/classes
[WARNING] /home/vagrant/komadu/komadu-master/axis2-client-core/target/generated-code/src/org/xmlsoap/schemas/soap/encoding/impl/ENTITIESImpl.java: Some input files use or override a deprecated API.
[WARNING] /home/vagrant/komadu/komadu-master/axis2-client-core/target/generated-code/src/org/xmlsoap/schemas/soap/encoding/impl/ENTITIESImpl.java: Recompile with -Xlint:deprecation for details.
[WARNING] /home/vagrant/komadu/komadu-master/axis2-client-core/target/generated-code/src/org/w3/www/ns/prov/impl/EntityImpl.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/vagrant/komadu/komadu-master/axis2-client-core/target/generated-code/src/org/w3/www/ns/prov/impl/EntityImpl.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ komadu-axis2-client-core ---
[WARNING] Using platform encoding (ANSI_X3.4-1968 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ komadu-axis2-client-core ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding ANSI_X3.4-1968, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /home/vagrant/komadu/komadu-master/axis2-client-core/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.6:test (default-test) @ komadu-axis2-client-core ---
[INFO] Surefire report directory: /home/vagrant/komadu/komadu-master/axis2-client-core/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running edu.indiana.d2i.komadu.axis2.client.KomaduTests
log4j:WARN No appenders could be found for logger (org.apache.axis2.description.AxisOperation).
log4j:WARN Please initialize the log4j system properly.
Giving 5 seconds for processing of notifications...
Resuming...


 Context workflow graph 


org.apache.axis2.AxisFault: java.lang.NoClassDefFoundError: org/openprovenance/prov/model/Other
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:375)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at edu.indiana.d2i.komadu.axis2.client.KomaduServiceStub.getContextWorkflowGraph(KomaduServiceStub.java:706)
	at edu.indiana.d2i.komadu.axis2.client.KomaduTests.testContextWorkflowGraph(KomaduTests.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)


 Activity Graph without context 


org.apache.axis2.AxisFault: java.lang.NoClassDefFoundError: org/openprovenance/prov/model/Other
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:375)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at edu.indiana.d2i.komadu.axis2.client.KomaduServiceStub.getActivityGraph(KomaduServiceStub.java:996)
	at edu.indiana.d2i.komadu.axis2.client.KomaduTests.testActivityGraph(KomaduTests.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)


 Agent Graph without context 

	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)

org.apache.axis2.AxisFault: java.lang.NoClassDefFoundError: org/openprovenance/prov/model/Other
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:375)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at edu.indiana.d2i.komadu.axis2.client.KomaduServiceStub.getAgentGraph(KomaduServiceStub.java:1240)
	at edu.indiana.d2i.komadu.axis2.client.KomaduTests.testAgentGraph(KomaduTests.java:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)


 Entity Graph without context 

	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)

org.apache.axis2.AxisFault: java.lang.NoClassDefFoundError: org/openprovenance/prov/model/Other
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:375)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
	at edu.indiana.d2i.komadu.axis2.client.KomaduServiceStub.getEntityGraph(KomaduServiceStub.java:350)
	at edu.indiana.d2i.komadu.axis2.client.KomaduTests.testEntityGraph(KomaduTests.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)


 Find Activity 


Found Activity: workflow1_2546


 Get Activity Detail 


Activity ID: workflow1_2546
Activity Type: WORKFLOW
Activity Context Service ID: null
Activity Timestep: 20
Activity Context Workflow ID: null
Activity Node ID: node1
Activity Instance Of: 33


 Find Entity 


Found File Entity
File URI : file://foo/bar/data1.txt_2546
File ID : File_130
File Creation Date : 2015-10-07T14:45:53.000Z
Found File Entity
File URI : file://foo/bar/coll_data1.txt_2546
File ID : File_135
File Creation Date : 2015-10-07T14:45:53.000Z


 Get Entity Detail 


Entity ID: File_135
File Name: coll_data1.txt_2546
File URI: file://foo/bar/coll_data1.txt_2546
File Creation Date: 2015-10-07T14:45:53.000Z
File Owner: 3
File MD5: dummy_md5_coll_data1.txt_2546
Tests run: 7, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 11.544 sec <<< FAILURE!

Results :

Failed tests: 
  testContextWorkflowGraph(edu.indiana.d2i.komadu.axis2.client.KomaduTests)
  testActivityGraph(edu.indiana.d2i.komadu.axis2.client.KomaduTests)
  testAgentGraph(edu.indiana.d2i.komadu.axis2.client.KomaduTests)
  testEntityGraph(edu.indiana.d2i.komadu.axis2.client.KomaduTests)

Tests run: 7, Failures: 4, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:17.660s
[INFO] Finished at: Wed Oct 07 14:46:00 UTC 2015
[INFO] Final Memory: 17M/158M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.6:test (default-test) on project komadu-axis2-client-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/vagrant/komadu/komadu-master/axis2-client-core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by Data2Insight** [comment]
Hello,

Thanks for trying out Komadu and posting your issue. It looks like prov-model and prov-xml libraries are not copied into tomcat/lib. Please follow the step below and try running the test again. 

Copy following jar files into {your_tomcat_home}/lib.
{your_home}/.m2/repository/org/openprovenance/prov/prov­model/0.4.0/prov­model­0.4.0
.jar 
{your_home}/.m2/repository/org/openprovenance/prov/prov­xml/0.4.0/prov­xml­0.4.0.jar 
{your_home}/.m2/repository/org/jvnet/jaxb2_commons/runtime/0.4.1.5/runtime­0.4.1.5.jar 
{your_home}/.m2/repository/commons­lang/commons­lang/2.6/commons­lang­2.6.jar 

Let us know whether this fixes the issue.

Thanks,
Isuru

**Comment by jihadbaeth** [comment]
It worked out, Thank you very much
