### ISSUE TITLE
"Unable to process raw notification" error

### ISSUE THREAD

**Issue by yucelts** [Data-to-Insight-Center/komadu#7]
Hi,

I am trying to build and run komadu on Windows 7. I followed the instructions and finally compiled the axis2-client-core. But I am getting the following errors on the server side. What might be the reason? I used the GRANT ALL ON and GRANT SELECT ON commands but these commands didn't solve the problem.

Thanks

20 Kas 2015 13:44:05,517 [http-8080-1] INFO  edu.indiana.d2i.komadu.service.KomaduServiceSkeleton  -Entity-Entity Relationship Added..
20 Kas 2015 13:44:05,595 [http-8080-1] INFO  edu.indiana.d2i.komadu.service.KomaduServiceSkeleton  -Entity-Entity Relationship Added..
20 Kas 2015 13:44:05,642 [AsynProc-0] ERROR edu.indiana.d2i.komadu.ingest.db.BaseDBIngester  -Unable to process raw notification with internalID 648
edu.indiana.d2i.komadu.ingest.IngestException: Max retries 10 for the lock reached for the object: collection2_1939
	at edu.indiana.d2i.komadu.util.KomaduUtils.manageDBLock(KomaduUtils.java:100)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngesterImplementer.addNewCollection(BaseDBIngesterImplementer.java:799)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngesterImplementer.addNewEntity(BaseDBIngesterImplementer.java:782)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngesterImplementer.storeEntityEntityRelationship(BaseDBIngesterImplementer.java:320)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngester.processNotifications(BaseDBIngester.java:143)
	at edu.indiana.d2i.komadu.ingest.AsyncRawNotificationProcessor.run(AsyncRawNotificationProcessor.java:99)
	at java.lang.Thread.run(Thread.java:724)

**Comment by isurues** [comment]
Hi,

It looks like Komadu has failed to acquire the lock to write to the
database. Most of the time this happens when there's something wrong with
the database. Could you please delete the database and create a fresh one
and grant permissions according to the steps provided in the documentation?

http://d2i.indiana.edu/sites/default/files/komaduuserguide.pdf

On the other hand, we haven't tested Komadu on Windows. But I think there's
nothing which prevents it from running properly on Windows. Please let us
know if you'll get this issue even after creating a new database. We'll
test it on Windows.

Thanks,
Isuru

**Comment by yucelts** [comment]
Hi, 

I deleted the komadu database and created a new one and grant permissions according to the komaduuserguide.pdf as you said but the problem still continues. It looks like to stem from a database problem but I couldn't find the problem.

Thanks.

**Comment by isurues** [comment]
Hi,

Could you please log into your mysql console and check whether there's any
data in exe_activity or exe_entity table? That will give us an idea about
whether the very first db write fails or it fails after few successful
writes. If the tables are empty, that means non of the writes have gone in.
In that case, could you please log into mysql using the username which is
used by Komadu and try to write some data into a table?

And are you using komadu trunk or 1.0 release which is available here?

https://github.com/Data-to-Insight-Center/komadu/releases

I'm sorry that I'm unable to do much from my side as I can't reproduce the
issue. But I'll try to install Komadu on a windows machine and check
whether this happens.

Thanks,
Isuru

**Comment by yucelts** [comment]
Hi Isuru,

I logged into the mysql console and checked the exe_activity and exe_entity tables. 
There wasn't any data in these tables. Then I tried to insert some data to these 
tables from the console and the data was added succesfully. If it helps you, 
I also checked the raw_notifications table and there was data in raw_notifications 
table. I am using komadu-1.0.

Thanks,
Yucel

**Comment by sevketarisu** [comment]
Hi yucelts, i got same error at first when i had installed komadu db to mysql server.
After some search, I recognized  that i had installed an older version of komadu install script.

Check this: In komadu_db_schema.sql file the flowing variable must be length of 7

> `DECLARE lockPrefix VARCHAR(7) DEFAULT "komadu.";`
