### ISSUE TITLE
 ERROR Lock not obtained after 10 retries for the lock reached for the object

### ISSUE THREAD

**Issue by sevketarisu** [Data-to-Insight-Center/komadu#9]
[raw_notification.txt](https://github.com/Data-to-Insight-Center/komadu/files/403155/raw_notification.txt)

Hi,
I am sending prov notifications via Komadu Webservice. I am getting error below after processing a few notifications successfully. I am sending 28 notification in 4 seconds. (about 7 notifications per second)

What could be the reason behind this error?  Thank you.
Note: raw_notification table is attached as html format.

30 Tem 2016 21:39:34,196 [AsynProc-1] ERROR edu.indiana.d2i.komadu.ingest.db.BaseDBIngester  -Unable to process raw notification with internalID 2
edu.indiana.d2i.komadu.ingest.IngestException: Lock not obtained after 10 retries for the lock reached for the object: DEVELOPER_2
	at edu.indiana.d2i.komadu.util.KomaduUtils.manageDBLock(KomaduUtils.java:124)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngesterImplementer.addNewAgent(BaseDBIngesterImplementer.java:730)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngesterImplementer.addNewFileEntity(BaseDBIngesterImplementer.java:894)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngesterImplementer.addNewEntity(BaseDBIngesterImplementer.java:772)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngesterImplementer.storeActivityEntityRelationship(BaseDBIngesterImplementer.java:205)
	at edu.indiana.d2i.komadu.ingest.db.BaseDBIngester.processNotifications(BaseDBIngester.java:128)
	at edu.indiana.d2i.komadu.ingest.AsyncRawNotificationProcessor.run(AsyncRawNotificationProcessor.java:99)
	at java.lang.Thread.run(Thread.java:744)

**Comment by bethplale** [comment]
HI Boris

glad to see you poking around.   Gabriel and Isuru are points of contact.  

Gabriel, Isuru, Boris is one of our strongest technical developer on HTRC; he’s working for UIUC.

beth

**Comment by isurues** [comment]
Hi, 

Thanks for your interest in Komadu and we are happy to help. Could you please send us some more details about your setup? MySQL version, whether you are using web services channel or RabbitMQ channel, and are you running both client and server on the same machine?

Thanks,
Isuru

**Comment by sevketarisu** [comment]
Hi Isuru,
Thanks for your reply
MySQL version: ver 14.14 Distrib 5.7.13, for Win64
I am using web services channel.  Mysql and tomcat server are running on different machines. (both windows)
And the client code which calls the komadu web service is running on same server with tomcat server.
(URL: http://localhost:8090/axis2/services/KomaduService)

Thansk

**Comment by sevketarisu** [comment]
Hi Isuru,
Did you be able to examine the "Lock not obtained after 10 retries" error?

**Comment by AhmetGurbuzz** [comment]
Hi @sevketarisu, after a lot of tryings, i have found that pdf file which says komadu had tested on ubuntu linux 12.04. Then i installed "ubuntu-12.04.5-desktop-amd64.iso" and komadu inside it. In this setup, i implemented komadu with same steps and hopefully it worked without any problem. In addition to this, I was setup ubuntu 16.04 lts at first step and The main difference between 12.04 and 16.04 installing steps was mysql-server-5.5 and mysql-server-5.7. The rest of all steps are same.
 I hope this will help you.

AhmetGurbuzz

[60-588-1-PB.pdf](https://github.com/Data-to-Insight-Center/komadu/files/1840651/60-588-1-PB.pdf)

**Comment by Gabriel-Zhou** [comment]
Hi @sevketarisu @AhmetGurbuzz ,

Thanks for the questions about Komadu DB ingester. I have tested Mysql Win V14.14 which is possible to report "Lock not obtained" exceptions. 

The best solution is to deploy MySQL database server 5.1 instead of Win V14.14 as backend provenance repository. Another parameter you can change is in the class /komadu/util/DBLockConstants to edit the MAX_RETRIES to test the JDBC connection.

Please let me know if you still meet any questions or problems.

Thanks!

Best,

Gabriel Zhou

**Comment by AhmetGurbuzz** [comment]
Hi @Gabriel-Zhou @sevketarisu,

It is glad to hear from you after a couple of hours from my comment. For now, I am using ubuntu linux 12.04 with mysql-server-5.5 and it's working fine for me. I am trying to write my own komaduclient class and sometimes need to build again with "sudo mvn clean install -o" at command line under 
../komadu/axis2-client-core.  However, sometimes testFindEntityAndDetail() test case is giving error. I am giving to my "komadu.log", "catalina.out" and "surefire-reports" here. I hope you can find the problem why it is. On the other hand, I have experienced that tomcat doesn't respond while i am building axis2-client-core. The way i see it, Tomcat is being tired :) after a few build but i am fixing it with stopping tomcat and reboot ubuntu linux :))
In the logs you will see the 1 test case error. I dont have any other errors.

Thanks for your interest,

AhmetGurbuzz
[komadu.log](https://github.com/Data-to-Insight-Center/komadu/files/1843427/komadu.log)
[edu.indiana.d2i.komadu.axis2.client.KomaduTests.txt](https://github.com/Data-to-Insight-Center/komadu/files/1843428/edu.indiana.d2i.komadu.axis2.client.KomaduTests.txt)
[catalina.log](https://github.com/Data-to-Insight-Center/komadu/files/1843435/catalina.log)

**Comment by Gabriel-Zhou** [comment]
Glad to hear the mysql issue is fixed. 

For tomcat, it would be better you restart the server by ./shutdown.sh and ./startup.sh after you re-deploy the axis2-client war file.

For your test case, it looks to me it is the ingested provenance notification exception. 
java.lang.NullPointerException
	at edu.indiana.d2i.komadu.axis2.client.KomaduTests.getFileName(KomaduTests.java:834)
Could you check if the file name of each provenance entity is valid in your provenance notification xml file?

Thank you!
